%% investigating S, |m| and rho* numercially with varying q

%% generate results
clear

N = 100; % set number of nodes
K = 8; % set degree

% set parameter ranges
q_vec = [0.1:0.1:2.5];
p = 0.15;

% set initial condition m = 0
initial_1 = 0.5;

% set maximum number of steps of model until it terminates
max_steps = 28000;

% set number of simulation repeats to average over
sim = 500;

% loop over q values
for i = 1:length(q_vec)

    % update current q value
    q = q_vec(i);

    % loop over s simulations
    for k = 1:sim

        % generate graph of fixed degree K with N nodes
        g = G_fixed_degree(N, K);

        % implement coevolutionary nonlinear voter model
        [adj_matrix, consensus_time, opinions_0, opinions_1, conflicting_edges] = coev_nonlinear_voter_model(g, p, q, initial_1, max_steps);

        % find the components of final state
        components = conncomp(graph(adj_matrix));

        % find the sizes of components
        component_sizes = histcounts(components, 1:max(components)+1);

        % store S, |m| and rho* values from each simulation
        s_vec(k) = max(component_sizes) / N;
        m_vec(k) = abs((length(opinions_1) - length(opinions_0)) / N);
        rho_vec(k) = sum(sum(conflicting_edges)) / sum(sum(adj_matrix));

    end

    % find average values of S, |m| and rho* over all simulations
    s_averaged(i) = sum(s_vec) / sim;
    m_averaged(i) = sum(m_vec) / sim;
    rho_averaged(i) = sum(rho_vec) / sim;

end

%% load results and plot graph for reproducibility
clear

% load saved data generated by previous section
load('num_varying_q.mat')

figure;
hold on
set(gca,'fontsize',16)
title('p = 0.15 (p < pc)', 'FontSize', 18)
xlabel('q', 'FontSize', 16)
grid on; grid minor
plot1 = plot(q_vec, s_averaged, '^-', 'Color','#4C60A9', 'LineWidth', 2, 'MarkerSize', 10);
plot2 = plot(q_vec, m_averaged, 'o-', 'Color','#DCAD04', 'LineWidth', 2, 'MarkerSize', 10);
plot3 = plot(q_vec, rho_averaged, 'square-', 'Color','#AF5F5A', 'LineWidth', 2, 'MarkerSize', 10);
legend([plot1, plot2, plot3], 'S', '|m|', '\rho*')
set(gca,'fontsize',16)